### ISSUE TITLE
Django - views.py 모델 optimizer 연결 트러블슈팅

### ISSUE THREAD

**Issue by dayeon1201** [Kiwoom-Kiosk/Kiwoom-Kiosk#8]
## 🛠 Issue

- [ ] views.py 에서 model def Adam, mse 코드 에러

## 📝 To-do

- [ ] load_model('age_model_3.h5') 코드 adam, mse 추가해보기
- [ ] cnn 모델에서 opt 수정
